name: lifeofafarmer
favicon: null
layout_spectrum: 0.48353832913562655
typography_spectrum: 0.39653096976689994
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5716692181304097
  lightness: 0.05366878630593419
  saturation: 0.7401365104597062
  rhythmicContrast: 0.5147382845170796
purpose: []
