name: lifeofafarmer
favicon: null
layout_spectrum: 0.25793
typography_spectrum: 0.59349
title: Life Of A Farmer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1a5774'
    - '#0e1f2a'
    - '#89929c'
    - '#6e0202'
  brandStrength: 0.5716692181304097
  lightness: 0.05366878630593419
  saturation: 0.7401365104597062
  rhythmicContrast: 0.5
purpose: []
